// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZSAIEa68nda-ztXSbS0PdCEEWA7vlBwI',
    appId: '1:991699212916:web:91d702df52db1b64d2cf21',
    messagingSenderId: '991699212916',
    projectId: 'madexam-50661',
    authDomain: 'madexam-50661.firebaseapp.com',
    storageBucket: 'madexam-50661.firebasestorage.app',
    measurementId: 'G-8NET0T21Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVuQLPnij_exAMFapGTX9m1d5nh8snxT8',
    appId: '1:991699212916:android:020227b1d11c1655d2cf21',
    messagingSenderId: '991699212916',
    projectId: 'madexam-50661',
    storageBucket: 'madexam-50661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWBaGJdDsvhspUTGP843xUo6hW-AHXzo',
    appId: '1:991699212916:ios:bee879830229e0a2d2cf21',
    messagingSenderId: '991699212916',
    projectId: 'madexam-50661',
    storageBucket: 'madexam-50661.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWBaGJdDsvhspUTGP843xUo6hW-AHXzo',
    appId: '1:991699212916:ios:bee879830229e0a2d2cf21',
    messagingSenderId: '991699212916',
    projectId: 'madexam-50661',
    storageBucket: 'madexam-50661.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZSAIEa68nda-ztXSbS0PdCEEWA7vlBwI',
    appId: '1:991699212916:web:3d6ff20aca0492dad2cf21',
    messagingSenderId: '991699212916',
    projectId: 'madexam-50661',
    authDomain: 'madexam-50661.firebaseapp.com',
    storageBucket: 'madexam-50661.firebasestorage.app',
    measurementId: 'G-9JQGWM0VQ8',
  );
}
